swagger: "2.0"
info:
  version: "0.0.1"
  title: Api Service
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /getChannelHistory:
    x-swagger-router-controller: channelHistory
    post:
      description: Returns history of channel founded by requested parameters
      operationId: getChannelHistory
      parameters:
        - in: body
          name: channel
          schema:
            type: object
            properties:
              name:
                type: string
              link:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BaseResponse"
  /addAccount:
    x-swagger-router-controller: account
    post:
      description: Adding row in account table with certain parameters
      operationId: addAccount
      parameters:
        - in: body
          name: user
          required: true
          schema:
            type: object
            required:
              - name
              - login
              - phone
            properties:
              name:
                type: string
              login:
                type: string
              phone:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BaseResponse"

  /channels:
    x-swagger-router-controller: channel
    get:
      description: Returns list of channels to the caller
      operationId: getChannels
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BaseResponse"
  /tests:
    x-swagger-router-controller: tests
    get:
      description: For testing and development. Must be deleted on production stage
      operationId: devTests
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BaseResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  BaseResponse:
    required:
      - current_timestamp
      - error
      - data
    properties:
      current_timestamp:
        type: string
      error:
        type: 
          - object
          - 'null'
      data:
        type: 
          - object
          - 'null'
