swagger: "2.0"
info:
  version: "0.0.1"
  title: Api Service
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /channels:
    x-swagger-router-controller: channel
    get:
      description: Returns list of channels to the caller
      operationId: getChannels
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BaseResponse"
  /tests:
    x-swagger-router-controller: test
    get:
      description: For testing and development. Must be deleted on production stage
      operationId: devTests
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BaseResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  BaseResponse:
    required:
      - current_timestamp
      - error
      - data
    properties:
      current_timestamp:
        type: string
      error:
        type: 
          - object
          - 'null'
      data:
        type: 
          - object
          - 'null'
